# Build the library on different platforms

name: Build

on:
  push:
    branches:
      - master
      - testCI
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: ON
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  ####################
  # Linux / macOS
  ####################

  build:
    name: ${{ matrix.name }} Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        cholmod: [ON, OFF]
        include:
          - os: macos-latest
            name: macOS
          - os: ubuntu-latest
            name: Linux
    steps:
      - uses: actions/checkout@v1

      - name: Dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt install libeigen3-dev coreutils libcholmod
      - name: Dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install eigen coreutils suite-sparse

      - name: Configure
        run:  cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DOPTIM_USE_CHOLMOD=${{ matrix.cholmod }}

      - name: Build
        run: cmake --build build --config Release -j $(nproc)

      - name: Run
        run: build/example/example
