name: Build

on:
  push:
    branches:
      - master
      - testCI
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: ON
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  ####################
  # Linux / macOS
  ####################

  build:
    name: ${{ matrix.name }} Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: macos-latest
            name: macOS
          - os: ubuntu-latest
            name: Linux
    steps:
      - uses: actions/checkout@v1

      - name: Dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt install libeigen3-dev coreutils
      - name: Dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install eigen coreutils

      - name: Configure
        run:  cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug -DENABLE_TEST_COVERAGE=ON -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build build --config Debug -j $(nproc)

      - name: Tests
        run:  |
          cd build
          ctest -C Debug

      - name: collect code coverage
        run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
